default:
  dataset,model: 'null,null'
  is_online: False
  is_offline: False
  prune_method: 'null'
  quan_method: 'null'

dataset,model:
  - 'null,null'
  - TinyImageNet,ResNet50
  - TinyImageNet,ResNet101
  - VOC,ResNet50SSD
  - VOC,VGGSSD
  - Cityscapes,DeepLabV3
  - Cityscapes,PSPNet
  - stanford-dogs,mbnet
  - VOC,yolov5

prune_method:
  - 'null'
  # - fpgm
  # - agp

quan_method:
  - 'null'
  # - fp16
  # - int8

support_combinations:
  TinyImageNet,ResNet50:
    - fpgm,null
    - agp,null
    - null,fp16
    - null,int8
    - fpgm,fp16
    - fpgm,int8
    - agp,fp16
    - agp,int8
  TinyImageNet,ResNet101:
    - fpgm,null
    - agp,null
    - null,fp16
    - null,int8
    - fpgm,fp16
    - fpgm,int8
    - agp,fp16
    - agp,int8
  VOC,ResNet50SSD:
    - fpgm,null
    - null,fp16
    - null,int8
    - fpgm,fp16
    - fpgm,int8
  VOC,VGGSSD:
    - fpgm,null
    - null,fp16
    - null,int8
    - fpgm,fp16
    - fpgm,int8
  Cityscapes,PSPNet:
    - fpgm,null
    - null,fp16
    - null,int8
    - fpgm,fp16
    - fpgm,int8
  Cityscapes,DeepLabV3:
    - fpgm,null
    - null,fp16
    - null,int8
    - fpgm,fp16
    - fpgm,int8
  stanford-dogs,mbnet:
    - fpgm,null
    - null,fp16
    - fpgm,fp16
  VOC,yolov5:
    - fpgm,null
    - null,fp16
    - fpgm,fp16


origin_performance:
  TinyImageNet,ResNet50:
    Accuracy: 61.80 %
    FLOPs: 334.05 M
    Infer_times: 23.87 ms
    Parameters: 23.86 M
    Storage: 95.94 MB
  TinyImageNet,ResNet101:
    Accuracy: 61.90 %
    FLOPs: 637.09 M
    Infer_times: 35.22 ms
    Parameters: 42.80 M
    Storage: 172.17 MB
  VOC,ResNet50SSD:
    mAP: 76.30 %
    FLOPs: 9.93 G
    Infer_times: 90.00 ms
    Parameters: 38.06 M
    Storage: 146.00 MB
  VOC,VGGSSD:
    mAP: 77.8 %
    FLOPs: 31.4 G
    Infer_times: 20.00 ms
    Parameters: 26.28 M
    Storage: 201.00 MB
  Cityscapes,PSPNet:
    mIoU: 77.30 %
    FLOPs: 728.84 G
    Infer_times: 0.1 s
    Parameters: 46.72 M
    Storage: 188 MB
  Cityscapes,DeepLabV3:
    mIoU: 76.21 %
    FLOPs: 633.17 G
    Infer_times: 0.01 s
    Parameters: 58.75 M
    Storage: 449 MB
  stanford-dogs,mbnet:
    Accuracy: 76.21 %
    FLOPs: 633.17 M
    Infer_times: 0.01 ms
    Parameters: 58.75 M
    Storage: 449 MB
  VOC,yolov5:
    map50: 78 %
    FLOPs: 16.11 G
    Infer_times: 1.54 ms
    Parameters: 7.07 M
    Storage: 13.8 MB


figures:
  TinyImageNet,ResNet50:
    # top_center, top_right, down_left, down_center, down_right
    var_names: [Accuracy, FLOPs, Infer_times, Parameters, Storage] # 输出文件logs.yaml中的变量名字
    titles: ['Accuracy', 'FLOPs', 'Infer_time', 'Parameters', 'Storage']
    baseline_legends: ['baseline accuracy/%', 'baseline FLOPs/M', 'baseline infer_time/ms', 'baseline parameters/M', 'baseline storage/MB']
    method_legends: ['method accuracy/%', 'method FLOPs/M', 'method infer_time/ms', 'method parameters/M', 'method storage/MB']
    baseline_colors: ['#FB3207', '#FB3207', '#FB3207', '#FB3207', '#FB3207']
    method_colors: ['#0780FB', '#0780FB', '#0780FB', '#0780FB', '#0780FB']
  TinyImageNet,ResNet101:
    # top_center, top_right, down_left, down_center, down_right
    var_names: [Accuracy, FLOPs, Infer_times, Parameters, Storage] # 输出文件logs.yaml中的变量名字
    titles: ['Accuracy', 'FLOPs', 'Infer_time', 'Parameters', 'Storage']
    baseline_legends: ['baseline accuracy/%', 'baseline FLOPs/M', 'baseline infer_time/ms', 'baseline parameters/M', 'baseline storage/MB']
    method_legends: ['method accuracy/%', 'method FLOPs/M', 'method infer_time/ms', 'method parameters/M', 'method storage/MB']
    baseline_colors: ['#FB3207', '#FB3207', '#FB3207', '#FB3207', '#FB3207']
    method_colors: ['#0780FB', '#0780FB', '#0780FB', '#0780FB', '#0780FB']
  VOC,ResNet50SSD:
    # top_center, top_right, down_left, down_center, down_right
    var_names: [mAP, FLOPs, Infer_times, Parameters, Storage] # 输出文件logs.yaml中的变量名字
    titles: ['mAP', 'FLOPs', 'Infer_time', 'Parameters', 'Storage']
    baseline_legends: ['baseline mAP/%', 'baseline FLOPs/G', 'baseline infer_time/ms', 'baseline parameters/M', 'baseline storage/MB']
    method_legends: ['method mAP/%', 'method FLOPs/G', 'method infer_time/ms', 'method parameters/M', 'method storage/MB']
    baseline_colors: ['#FB3207', '#FB3207', '#FB3207', '#FB3207', '#FB3207']
    method_colors: ['#0780FB', '#0780FB', '#0780FB', '#0780FB', '#0780FB']
  VOC,VGGSSD:
    # top_center, top_right, down_left, down_center, down_right
    var_names: [mAP, FLOPs, Infer_times, Parameters, Storage] # 输出文件logs.yaml中的变量名字
    titles: ['mAP', 'FLOPs', 'Infer_time', 'Parameters', 'Storage']
    baseline_legends: ['baseline mAP/%', 'baseline FLOPs/G', 'baseline infer_time/ms', 'baseline parameters/M', 'baseline storage/MB']
    method_legends: ['method mAP/%', 'method FLOPs/G', 'method infer_time/ms', 'method parameters/M', 'method storage/MB']
    baseline_colors: ['#FB3207', '#FB3207', '#FB3207', '#FB3207', '#FB3207']
    method_colors: ['#0780FB', '#0780FB', '#0780FB', '#0780FB', '#0780FB']
  Cityscapes,PSPNet:
    # top_center, top_right, down_left, down_center, down_right
    var_names: [mIoU, FLOPs, Infer_times, Parameters, Storage] # 输出文件logs.yaml中的变量名字
    titles: ['mIoU', 'FLOPs', 'Infer_time', 'Parameters', 'Storage']
    baseline_legends: ['baseline mIoU/%', 'baseline FLOPs/M', 'baseline infer_time/s', 'baseline parameters/M', 'baseline storage/MB']
    method_legends: ['method mIoU/%', 'method FLOPs/M', 'method infer_time/s', 'method parameters/M', 'method storage/MB']
    baseline_colors: ['#FB3207', '#FB3207', '#FB3207', '#FB3207', '#FB3207']
    method_colors: ['#0780FB', '#0780FB', '#0780FB', '#0780FB', '#0780FB']
  Cityscapes,DeepLabV3:
    # top_center, top_right, down_left, down_center, down_right
    var_names: [mIoU, FLOPs, Infer_times, Parameters, Storage] # 输出文件logs.yaml中的变量名字
    titles: ['mIoU', 'FLOPs', 'Infer_time', 'Parameters', 'Storage']
    baseline_legends: ['baseline mIoU/%', 'baseline FLOPs/M', 'baseline infer_time/s', 'baseline parameters/M', 'baseline storage/MB']
    method_legends: ['method mIoU/%', 'method FLOPs/M', 'method infer_time/s', 'method parameters/M', 'method storage/MB']
    baseline_colors: ['#FB3207', '#FB3207', '#FB3207', '#FB3207', '#FB3207']
    method_colors: ['#0780FB', '#0780FB', '#0780FB', '#0780FB', '#0780FB']
  stanford-dogs,mbnet:
    # top_center, top_right, down_left, down_center, down_right
    var_names: [Accuracy, FLOPs, Infer_times, Parameters, Storage] # 输出文件logs.yaml中的变量名字
    titles: ['Accuracy', 'FLOPs', 'Infer_time', 'Parameters', 'Storage']
    baseline_legends: ['baseline accuracy/%', 'baseline FLOPs/M', 'baseline infer_time/ms', 'baseline parameters/M', 'baseline storage/MB']
    method_legends: ['method accuracy/%', 'method FLOPs/M', 'method infer_time/ms', 'method parameters/M', 'method storage/MB']
    baseline_colors: ['#FB3207', '#FB3207', '#FB3207', '#FB3207', '#FB3207']
    method_colors: ['#0780FB', '#0780FB', '#0780FB', '#0780FB', '#0780FB']
  VOC,yolov5:
    # top_center, top_right, down_left, down_center, down_right
    var_names: [map50, FLOPs, Infer_times, Parameters, Storage] # 输出文件logs.yaml中的变量名字
    titles: ['map50', 'FLOPs', 'Infer_time', 'Parameters', 'Storage']
    baseline_legends: ['baseline map50/%', 'baseline FLOPs/G', 'baseline infer_time/ms', 'baseline parameters/M', 'baseline storage/MB']
    method_legends: ['method map50/%', 'method FLOPs/G', 'method infer_time/ms', 'method parameters/M', 'method storage/MB']
    baseline_colors: ['#FB3207', '#FB3207', '#FB3207', '#FB3207', '#FB3207']
    method_colors: ['#0780FB', '#0780FB', '#0780FB', '#0780FB', '#0780FB']

shell_path:
  TinyImageNet,ResNet50: algorithms/compression/nets/ResNet50/shell/compress.sh
  TinyImageNet,ResNet101: algorithms/compression/nets/ResNet50/shell/compress.sh
  VOC,ResNet50SSD: algorithms/compression/nets/ResNet50_SSD/shell/compress.sh
  VOC,VGGSSD: algorithms/compression/nets/VGG_SSD/shell/compress.sh
  Cityscapes,PSPNet: algorithms/compression/nets/PSPNet/shell/compress.sh
  Cityscapes,DeepLabV3: algorithms/compression/nets/DeepLabV3/shell/compress.sh
  stanford-dogs,mbnet: algorithms/compression/nets/mbnet_comp/shell/compress.sh
  VOC,yolov5: algorithms/compression/nets/yolov5_7/shell/compress.sh

img_size:
  TinyImageNet,ResNet50: [64, 64]
  TinyImageNet,ResNet101: [64, 64]
  VOC,ResNet50SSD: [300, 300]
  VOC,VGGSSD: [300, 300]
  Cityscapes,PSPNet: [713, 713]
  Cityscapes,DeepLabV3: [513, 513]
  stanford-dogs,mbnet: [640, 640]
  VOC,yolov5: [640, 640]
