default_setting:
  TinyImageNet,ResNet50:
    ft_lr: 0.001
    ft_bs: 128
    ft_epochs: 10
    prune_sparisity: 0.2
    gpus: "0"
  
  TinyImageNet,ResNet101:
    ft_lr: 0.001
    ft_bs: 128
    ft_epochs: 10
    prune_sparisity: 0.2
    gpus: "0"
  
  VOC,ResNet50SSD:
    ft_lr: 0.001
    ft_bs: 32
    ft_epochs: 25
    prune_sparisity: 0.2
    gpus: "0"
    
  VOC,VGGSSD:
    ft_lr: 0.001
    ft_bs: 128
    ft_epochs: 10
    prune_sparisity: 0.2
    gpus: "0"

  Cityscapes,PSPNet:
    ft_lr: 0.01
    ft_bs: 6
    ft_epochs: 100
    prune_sparisity: 0.3
    gpus: "0"

  Cityscapes,DeepLabV3:
    ft_lr: 0.01
    ft_bs: 16
    ft_epochs: 100
    prune_sparisity: 0.3
    gpus: "0"
  
  stanford-dogs,mbnet:
    ft_lr: 1e-4
    ft_bs: 32
    ft_epochs: 2
    prune_sparisity: 0.2
    gpus: "0"

  VOC,yolov5:
    ft_lr: 0.01
    ft_bs: 32
    ft_epochs: 1
    prune_sparisity: 0.3
    gpus: "0"
