name: star
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - scipy
  - matplotlib
  - tensorboard
  - pyyaml
  - imageio
  - tqdm
  - pandas
  - ipython
  - cython
  - pytorch=1.10.1
  - torchvision=0.11.2
  - torchaudio=0.10.1
  - cudatoolkit=11.3
  - werkzeug