MODEL:
  TYPE: ssd_res50
  SIZE: '300'
  REFINE: False
  CONV_BODY: resnet.SSDResnet101
  NUM_CLASSES: 21
  LOAD_PRETRAINED_WEIGHTS: True
  PRETRAIN_WEIGHTS: './weights/pretrained_models/resnet101-5d3b4d8f.pth'

TRAIN:
  OVERLAP: 0.5
  BGR_MEAN: [104, 117, 123]
  BATCH_SIZE: 32
  OHEM: True
  NEG_RATIO: 3
  WARMUP: True
  WARMUP_EPOCH: 2
  TRAIN_ON: True


SMALL:
  FEATURE_MAPS: [[38, 38], [19, 19], [10, 10], [5, 5], [3, 3], [1, 1]]
  ARM_CHANNELS: [512, 1024, 512, 256, 256, 256]
  NUM_ANCHORS: [4, 6, 6, 6, 4, 4]
  STEPS: [[8, 8], [16, 16], [32, 32], [64, 64], [100, 100], [300, 300]]
  MIN_SIZES: [30, 60, 111, 162, 213, 264]
  MAX_SIZES: [60, 111, 162, 213, 264, 315]
  ASPECT_RATIOS : [[2, 0.5], [2, 3, 0.5, 0.333], [2, 3, 0.5, 0.333], [2, 3, 0.5, 0.333], [2, 0.5], [2, 0.5]]
  VARIANCE : [0.1, 0.2]
  CLIP: True
  IMG_WH: [300, 300]
  INPUT_FIXED: True # if you want to input different size, you need to set this False.
  USE_MAX_SIZE: True

BIG:
  FEATURE_MAPS: [[64, 64], [32, 32], [16, 16], [8, 8], [4, 4], [2, 2], [1, 1]]
  ARM_CHANNELS: [512, 1024, 512, 256, 256, 256, 256]
  NUM_ANCHORS: [4, 6, 6, 6, 6, 4, 4]
  STEPS: [[8, 8], [16, 16], [32, 32], [64, 64], [128, 128], [256, 256], [512, 512]]
  MIN_SIZES: [35.84, 76.8, 153.6,  230.4, 307.2, 384.0, 460.8]
  MAX_SIZES: [76.8, 153.6, 230.4, 307.2, 384.0, 460.8, 537.6]
  ASPECT_RATIOS : [[2, 0.5], [2, 3, 0.5, 0.333], [2, 3, 0.5, 0.333], [2, 3, 0.5, 0.333], [2, 3, 0.5, 0.333], [2, 0.5], [2, 0.5]]

  CLIP: True
  IMG_WH: [512, 512]
  INPUT_FIXED: True # if you want to input different size, you need to set this False.
  USE_MAX_SIZE: True

SOLVER:
  WEIGHT_DECAY: 0.0005
  BASE_LR: 0.001
  GAMMA: 0.1
  MOMENTUM: 0.9
  EPOCH_STEPS: [0, 150, 200]  
  END_EPOCH: 250
  START_EPOCH: 0

DATASETS:
  TRAIN_TYPE: [['0712', '0712_trainval']]
  VAL_TYPE: [['0712', '2007_test']]
  DATAROOT: 'data/datasets/VOCdevkit0712/'
  DATA_TYPE: 'VOC'
  SETS:
    VOC: [['0712', '0712_trainval']]
    VOC0712PLUS: [['0712', '0712_trainval_test']]
    VOC0712: [['2012', '2012_trainval']]
    COCO: [['2014', 'train'], ['2014', 'valminusminival']]
    VOC2007: [['0712', "2007_test"]]
    COCOval: [['2014', 'minival']]
    VOCROOT: 'data/datasets/VOCdevkit0712/'
    COCOROOT: 'data/datasets/coco2015'
  
TEST:
  INPUT_WH: [300, 300]
  CONFIDENCE_THRESH: 0.01
  NMS_OVERLAP: 0.45
  BATCH_SIZE: 16
  




