# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'classify_nas.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(896, 947)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(250, 0))
        self.widget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 350))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 350))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 85))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.comboBox_dataset = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_dataset.setObjectName("comboBox_dataset")
        self.comboBox_dataset.addItem("")
        self.comboBox_dataset.addItem("")
        self.verticalLayout_12.addWidget(self.comboBox_dataset)
        self.verticalLayout_11.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 85))
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_online = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_online.setObjectName("checkBox_online")
        self.horizontalLayout_3.addWidget(self.checkBox_online)
        self.checkBox_offline = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_offline.setObjectName("checkBox_offline")
        self.horizontalLayout_3.addWidget(self.checkBox_offline)
        self.verticalLayout_11.addWidget(self.groupBox_4)
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_10.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_2 = QtWidgets.QLabel(self.groupBox_10)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_14.addWidget(self.label_2)
        self.comboBox_method = QtWidgets.QComboBox(self.groupBox_10)
        self.comboBox_method.setObjectName("comboBox_method")
        self.comboBox_method.addItem("")
        self.comboBox_method.addItem("")
        self.comboBox_method.addItem("")
        self.verticalLayout_14.addWidget(self.comboBox_method)
        self.verticalLayout_11.addWidget(self.groupBox_10)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.verticalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_start = QtWidgets.QPushButton(self.widget)
        self.pushButton_start.setMaximumSize(QtCore.QSize(100, 40))
        self.pushButton_start.setObjectName("pushButton_start")
        self.horizontalLayout_4.addWidget(self.pushButton_start)
        self.pushButton_reset = QtWidgets.QPushButton(self.widget)
        self.pushButton_reset.setMaximumSize(QtCore.QSize(100, 40))
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.horizontalLayout_4.addWidget(self.pushButton_reset)
        self.verticalLayout_16.addLayout(self.horizontalLayout_4)
        self.label_status = QtWidgets.QLabel(self.widget)
        self.label_status.setMinimumSize(QtCore.QSize(0, 50))
        self.label_status.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_status.setText("")
        self.label_status.setObjectName("label_status")
        self.verticalLayout_16.addWidget(self.label_status)
        self.verticalLayout_5.addLayout(self.verticalLayout_16)
        spacerItem = QtWidgets.QSpacerItem(20, 300, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox_5 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 300))
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 300))
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_results = QtWidgets.QLabel(self.groupBox_7)
        self.label_results.setMinimumSize(QtCore.QSize(0, 50))
        self.label_results.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_results.setText("")
        self.label_results.setObjectName("label_results")
        self.horizontalLayout_6.addWidget(self.label_results)
        self.verticalLayout_13.addWidget(self.groupBox_7)
        self.horizontalLayout_7.addWidget(self.groupBox_5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5.addWidget(self.widget)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_hyper_param = QtWidgets.QPushButton(self.tab)
        self.pushButton_hyper_param.setObjectName("pushButton_hyper_param")
        self.verticalLayout_7.addWidget(self.pushButton_hyper_param)
        self.textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_7.addWidget(self.textBrowser)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.scrollArea_train_loss = QtWidgets.QScrollArea(self.tab)
        self.scrollArea_train_loss.setWidgetResizable(True)
        self.scrollArea_train_loss.setObjectName("scrollArea_train_loss")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 133, 403))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea_train_loss.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea_train_loss)
        self.scrollArea_train_acc = QtWidgets.QScrollArea(self.tab)
        self.scrollArea_train_acc.setWidgetResizable(True)
        self.scrollArea_train_acc.setObjectName("scrollArea_train_acc")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 133, 403))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea_train_acc.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout.addWidget(self.scrollArea_train_acc)
        self.verticalLayout_9.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.scrollArea_lr = QtWidgets.QScrollArea(self.tab)
        self.scrollArea_lr.setWidgetResizable(True)
        self.scrollArea_lr.setObjectName("scrollArea_lr")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 175, 400))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.scrollArea_lr.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_8.addWidget(self.scrollArea_lr)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.scrollArea_valid_loss = QtWidgets.QScrollArea(self.tab)
        self.scrollArea_valid_loss.setWidgetResizable(True)
        self.scrollArea_valid_loss.setObjectName("scrollArea_valid_loss")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 178, 402))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.scrollArea_valid_loss.setWidget(self.scrollAreaWidgetContents_5)
        self.horizontalLayout_2.addWidget(self.scrollArea_valid_loss)
        self.scrollArea_valid_acc = QtWidgets.QScrollArea(self.tab)
        self.scrollArea_valid_acc.setWidgetResizable(True)
        self.scrollArea_valid_acc.setObjectName("scrollArea_valid_acc")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 177, 402))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.scrollArea_valid_acc.setWidget(self.scrollAreaWidgetContents_6)
        self.horizontalLayout_2.addWidget(self.scrollArea_valid_acc)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.groupBox_8)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.verticalLayout_4.addWidget(self.graphicsView_2)
        self.verticalLayout_3.addWidget(self.groupBox_8)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.groupBox_9)
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.horizontalLayout_15.addWidget(self.graphicsView_3)
        self.verticalLayout_3.addWidget(self.groupBox_9)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setMaximumSize(QtCore.QSize(530, 550))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox_2)
        self.graphicsView.setMaximumSize(QtCore.QSize(500, 500))
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_10.addWidget(self.graphicsView)
        self.horizontalLayout_9.addWidget(self.groupBox_2)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setMaximumSize(QtCore.QSize(450, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.scrollArea_11 = QtWidgets.QScrollArea(self.groupBox_6)
        self.scrollArea_11.setWidgetResizable(True)
        self.scrollArea_11.setObjectName("scrollArea_11")
        self.scrollAreaWidgetContents_8 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_8.setGeometry(QtCore.QRect(0, 0, 300, 782))
        self.scrollAreaWidgetContents_8.setObjectName("scrollAreaWidgetContents_8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_8)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_5 = QtWidgets.QWidget(self.scrollAreaWidgetContents_8)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_14.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_14.addWidget(self.lineEdit)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.widget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents_8)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.widget_2.setFont(font)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_10 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_12.addWidget(self.lineEdit_2)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents_8)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_8 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_13.addWidget(self.label_8)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_13.addWidget(self.lineEdit_3)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.scrollAreaWidgetContents_8)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_9 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_11.addWidget(self.label_9)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_11.addWidget(self.lineEdit_4)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.scrollArea_11.setWidget(self.scrollAreaWidgetContents_8)
        self.horizontalLayout_8.addWidget(self.scrollArea_11)
        self.horizontalLayout_9.addWidget(self.groupBox_6)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea_feature_map = QtWidgets.QScrollArea(self.tab_7)
        self.scrollArea_feature_map.setWidgetResizable(True)
        self.scrollArea_feature_map.setObjectName("scrollArea_feature_map")
        self.scrollAreaWidgetContents_16 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_16.setGeometry(QtCore.QRect(0, 0, 558, 787))
        self.scrollAreaWidgetContents_16.setObjectName("scrollAreaWidgetContents_16")
        self.scrollArea_feature_map.setWidget(self.scrollAreaWidgetContents_16)
        self.verticalLayout.addWidget(self.scrollArea_feature_map)
        self.pushButton_refresh = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_refresh.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.verticalLayout.addWidget(self.pushButton_refresh)
        self.tabWidget.addTab(self.tab_7, "")
        self.horizontalLayout_5.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 896, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "搜索配置"))
        self.groupBox_3.setTitle(_translate("MainWindow", "数据集"))
        self.comboBox_dataset.setItemText(0, _translate("MainWindow", "null"))
        self.comboBox_dataset.setItemText(1, _translate("MainWindow", "CIFAR-10"))
        self.groupBox_4.setTitle(_translate("MainWindow", "模式"))
        self.checkBox_online.setText(_translate("MainWindow", "在线"))
        self.checkBox_offline.setText(_translate("MainWindow", "离线"))
        self.groupBox_10.setTitle(_translate("MainWindow", "方法"))
        self.label_2.setText(_translate("MainWindow", "搜索"))
        self.comboBox_method.setItemText(0, _translate("MainWindow", "null"))
        self.comboBox_method.setItemText(1, _translate("MainWindow", "DARTS"))
        self.comboBox_method.setItemText(2, _translate("MainWindow", "GDAS"))
        self.pushButton_start.setText(_translate("MainWindow", "确定"))
        self.pushButton_reset.setText(_translate("MainWindow", "重置"))
        self.groupBox_5.setTitle(_translate("MainWindow", "结果输出"))
        self.groupBox_7.setTitle(_translate("MainWindow", "搜索后指标"))
        self.pushButton_hyper_param.setText(_translate("MainWindow", "超参数设置"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "训练可视化"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Normal Cell"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Reduction Cell"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "模型可视化"))
        self.groupBox_2.setTitle(_translate("MainWindow", "数据图片"))
        self.groupBox_6.setTitle(_translate("MainWindow", "分类结果"))
        self.label.setText(_translate("MainWindow", "method:                "))
        self.label_10.setText(_translate("MainWindow", "target_class:        "))
        self.label_8.setText(_translate("MainWindow", "predict_class:      "))
        self.label_9.setText(_translate("MainWindow", "predict latency:   "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "推理可视化"))
        self.pushButton_refresh.setText(_translate("MainWindow", "显示特征图"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "特征图可视化"))


