# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'compression.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1444, 973)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.leftFrame = QtWidgets.QWidget(self.centralwidget)
        self.leftFrame.setMinimumSize(QtCore.QSize(250, 0))
        self.leftFrame.setMaximumSize(QtCore.QSize(300, 16777215))
        self.leftFrame.setObjectName("leftFrame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.leftFrame)
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_6.setContentsMargins(-1, -1, 1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.leftFrame)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 350))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 350))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 85))
        self.groupBox_5.setObjectName("groupBox_5")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox.setGeometry(QtCore.QRect(11, 40, 191, 25))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.groupBox_5)
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_12.setMaximumSize(QtCore.QSize(16777215, 85))
        self.groupBox_12.setObjectName("groupBox_12")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.groupBox_12)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout_12.addWidget(self.checkBox_4)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_12.addWidget(self.checkBox_3)
        self.verticalLayout.addWidget(self.groupBox_12)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_6.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox_6.setObjectName("groupBox_6")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_6)
        self.layoutWidget.setGeometry(QtCore.QRect(13, 30, 191, 58))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.comboBox_5 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.setItemText(3, "")
        self.gridLayout_3.addWidget(self.comboBox_5, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 1, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_4, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_6)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_start = QtWidgets.QPushButton(self.leftFrame)
        self.pushButton_start.setMaximumSize(QtCore.QSize(100, 40))
        self.pushButton_start.setObjectName("pushButton_start")
        self.horizontalLayout_6.addWidget(self.pushButton_start)
        self.pushButton_reset = QtWidgets.QPushButton(self.leftFrame)
        self.pushButton_reset.setMaximumSize(QtCore.QSize(100, 40))
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.horizontalLayout_6.addWidget(self.pushButton_reset)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.label_7 = QtWidgets.QLabel(self.leftFrame)
        self.label_7.setMinimumSize(QtCore.QSize(0, 50))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        spacerItem = QtWidgets.QSpacerItem(20, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_6.addItem(spacerItem)
        self.groupBox_2 = QtWidgets.QGroupBox(self.leftFrame)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 350))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 400))
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 190, 238, 151))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.verticalLayout_4.addWidget(self.label_17)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 30, 241, 151))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(12, 32, 214, 111))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.horizontalLayout_5.addWidget(self.leftFrame)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_5.addWidget(self.line)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_7.addWidget(self.pushButton_2)
        self.textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_7.addWidget(self.textBrowser)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 373, 421))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 372, 421))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout.addWidget(self.scrollArea_2)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.tab)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 372, 420))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.horizontalLayout_2.addWidget(self.scrollArea_4)
        self.scrollArea_5 = QtWidgets.QScrollArea(self.tab)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 373, 420))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.horizontalLayout_2.addWidget(self.scrollArea_5)
        self.scrollArea_6 = QtWidgets.QScrollArea(self.tab)
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 372, 420))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_6)
        self.horizontalLayout_2.addWidget(self.scrollArea_6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.scrollArea_7 = QtWidgets.QScrollArea(self.tab_3)
        self.scrollArea_7.setWidgetResizable(True)
        self.scrollArea_7.setObjectName("scrollArea_7")
        self.scrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.scrollArea_7.setWidget(self.scrollAreaWidgetContents_7)
        self.verticalLayout_13.addWidget(self.scrollArea_7)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_modelvis = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_modelvis.setObjectName("pushButton_modelvis")
        self.horizontalLayout_7.addWidget(self.pushButton_modelvis)
        self.pushButton_compmodelvis = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_compmodelvis.setObjectName("pushButton_compmodelvis")
        self.horizontalLayout_7.addWidget(self.pushButton_compmodelvis)
        self.verticalLayout_13.addLayout(self.horizontalLayout_7)
        self.tabWidget.addTab(self.tab_3, "")
        self.horizontalLayout_5.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1444, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "模型压缩"))
        self.groupBox.setTitle(_translate("MainWindow", "压缩配置"))
        self.groupBox_5.setTitle(_translate("MainWindow", "数据集和模型"))
        self.comboBox.setItemText(0, _translate("MainWindow", "null,null"))
        self.groupBox_12.setTitle(_translate("MainWindow", "模式"))
        self.checkBox_4.setText(_translate("MainWindow", "在线"))
        self.checkBox_3.setText(_translate("MainWindow", "离线"))
        self.groupBox_6.setTitle(_translate("MainWindow", "方法"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "null"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "fp16"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "int8"))
        self.label_5.setText(_translate("MainWindow", "量化"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "null"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "l1"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "l2"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "agp"))
        self.label_4.setText(_translate("MainWindow", "剪枝"))
        self.pushButton_start.setText(_translate("MainWindow", "确定"))
        self.pushButton_reset.setText(_translate("MainWindow", "重置"))
        self.groupBox_2.setTitle(_translate("MainWindow", "结果输出"))
        self.groupBox_4.setTitle(_translate("MainWindow", "压缩后指标"))
        self.groupBox_3.setTitle(_translate("MainWindow", "压缩前指标"))
        self.pushButton_2.setText(_translate("MainWindow", "超参数设置"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:9pt;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "压缩可视化"))
        self.pushButton_modelvis.setText(_translate("MainWindow", "显示压缩前网络和特征图"))
        self.pushButton_compmodelvis.setText(_translate("MainWindow", "显示压缩后网络和特征图"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "网络和特征图可视化"))


