# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hyperparameters_setting.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(890, 337)
        self.label_base = QtWidgets.QLabel(Dialog)
        self.label_base.setGeometry(QtCore.QRect(40, 40, 131, 16))
        self.label_base.setObjectName("label_base")
        self.lineEdit_ft_bs = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_ft_bs.setGeometry(QtCore.QRect(230, 110, 171, 21))
        self.lineEdit_ft_bs.setText("")
        self.lineEdit_ft_bs.setObjectName("lineEdit_ft_bs")
        self.label_ft_bs = QtWidgets.QLabel(Dialog)
        self.label_ft_bs.setGeometry(QtCore.QRect(60, 110, 150, 20))
        self.label_ft_bs.setObjectName("label_ft_bs")
        self.lineEdit_output_path = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_output_path.setGeometry(QtCore.QRect(610, 110, 171, 21))
        self.lineEdit_output_path.setText("")
        self.lineEdit_output_path.setObjectName("lineEdit_output_path")
        self.label_output_path = QtWidgets.QLabel(Dialog)
        self.label_output_path.setGeometry(QtCore.QRect(480, 110, 111, 20))
        self.label_output_path.setObjectName("label_output_path")
        self.pushButton_output_path = QtWidgets.QPushButton(Dialog)
        self.pushButton_output_path.setGeometry(QtCore.QRect(790, 110, 81, 21))
        self.pushButton_output_path.setObjectName("pushButton_output_path")
        self.pushButton_confirm = QtWidgets.QPushButton(Dialog)
        self.pushButton_confirm.setGeometry(QtCore.QRect(60, 260, 121, 31))
        self.pushButton_confirm.setObjectName("pushButton_confirm")
        self.pushButton_reset = QtWidgets.QPushButton(Dialog)
        self.pushButton_reset.setGeometry(QtCore.QRect(360, 260, 121, 31))
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.pushButton_quit = QtWidgets.QPushButton(Dialog)
        self.pushButton_quit.setGeometry(QtCore.QRect(670, 260, 121, 31))
        self.pushButton_quit.setObjectName("pushButton_quit")
        self.label_input_path = QtWidgets.QLabel(Dialog)
        self.label_input_path.setGeometry(QtCore.QRect(480, 150, 111, 20))
        self.label_input_path.setObjectName("label_input_path")
        self.lineEdit_input_path = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_input_path.setGeometry(QtCore.QRect(610, 150, 171, 21))
        self.lineEdit_input_path.setText("")
        self.lineEdit_input_path.setObjectName("lineEdit_input_path")
        self.label_dataset_path = QtWidgets.QLabel(Dialog)
        self.label_dataset_path.setGeometry(QtCore.QRect(480, 190, 111, 20))
        self.label_dataset_path.setObjectName("label_dataset_path")
        self.lineEdit_dataset_path = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_dataset_path.setGeometry(QtCore.QRect(610, 190, 171, 21))
        self.lineEdit_dataset_path.setText("")
        self.lineEdit_dataset_path.setObjectName("lineEdit_dataset_path")
        self.label_gpus = QtWidgets.QLabel(Dialog)
        self.label_gpus.setGeometry(QtCore.QRect(480, 70, 111, 20))
        self.label_gpus.setObjectName("label_gpus")
        self.lineEdit_gpus = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_gpus.setEnabled(True)
        self.lineEdit_gpus.setGeometry(QtCore.QRect(610, 70, 171, 21))
        self.lineEdit_gpus.setText("")
        self.lineEdit_gpus.setObjectName("lineEdit_gpus")
        self.pushButton_input_path = QtWidgets.QPushButton(Dialog)
        self.pushButton_input_path.setGeometry(QtCore.QRect(790, 150, 81, 21))
        self.pushButton_input_path.setObjectName("pushButton_input_path")
        self.pushButton_dataset_path = QtWidgets.QPushButton(Dialog)
        self.pushButton_dataset_path.setGeometry(QtCore.QRect(790, 190, 81, 21))
        self.pushButton_dataset_path.setObjectName("pushButton_dataset_path")
        self.label_ft_epochs = QtWidgets.QLabel(Dialog)
        self.label_ft_epochs.setGeometry(QtCore.QRect(60, 150, 150, 20))
        self.label_ft_epochs.setObjectName("label_ft_epochs")
        self.lineEdit_ft_epochs = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_ft_epochs.setGeometry(QtCore.QRect(230, 150, 171, 21))
        self.lineEdit_ft_epochs.setObjectName("lineEdit_ft_epochs")
        self.lineEdit_prune_sparisity = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_prune_sparisity.setGeometry(QtCore.QRect(230, 70, 171, 21))
        self.lineEdit_prune_sparisity.setObjectName("lineEdit_prune_sparisity")
        self.label_prune_sparisity = QtWidgets.QLabel(Dialog)
        self.label_prune_sparisity.setGeometry(QtCore.QRect(60, 70, 150, 20))
        self.label_prune_sparisity.setObjectName("label_prune_sparisity")
        self.lineEdit_ft_lr = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_ft_lr.setGeometry(QtCore.QRect(230, 190, 171, 21))
        self.lineEdit_ft_lr.setText("")
        self.lineEdit_ft_lr.setObjectName("lineEdit_ft_lr")
        self.label_ft_lr = QtWidgets.QLabel(Dialog)
        self.label_ft_lr.setGeometry(QtCore.QRect(60, 190, 160, 20))
        self.label_ft_lr.setObjectName("label_ft_lr")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Hyper-parameters"))
        self.label_base.setText(_translate("Dialog", "Hyper-parameters"))
        self.label_ft_bs.setText(_translate("Dialog", "finetune batch size："))
        self.label_output_path.setText(_translate("Dialog", "output path："))
        self.pushButton_output_path.setText(_translate("Dialog", "Choose"))
        self.pushButton_confirm.setText(_translate("Dialog", "OK"))
        self.pushButton_reset.setText(_translate("Dialog", "Reset"))
        self.pushButton_quit.setText(_translate("Dialog", "Exit"))
        self.label_input_path.setText(_translate("Dialog", "input path："))
        self.label_dataset_path.setText(_translate("Dialog", "dataset path："))
        self.label_gpus.setText(_translate("Dialog", "gpus："))
        self.pushButton_input_path.setText(_translate("Dialog", "Choose"))
        self.pushButton_dataset_path.setText(_translate("Dialog", "Choose"))
        self.label_ft_epochs.setText(_translate("Dialog", "finetune epochs："))
        self.label_prune_sparisity.setText(_translate("Dialog", "prune sparisity："))
        self.label_ft_lr.setText(_translate("Dialog", "finetune learning rate："))


